<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7:
    roles:
      - server-el7
      - default
    platform: el-7-x86_64
    box:     centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

  el6:
    roles:
      - server-el6
    platform: el-6-x86_64
    box:     centos/6
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

  el8:
    roles:
      - server-el8
    platform: el-8-x86_64
    box:     generic/centos8
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
  synced_folder: disabled
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
